# Generated by Django 3.1.6 on 2021-02-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=250)),
                ('room_id', models.PositiveIntegerField()),
                ('availability', models.BooleanField()),
                ('full_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('zipcode', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=2)),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('card_number', models.PositiveIntegerField()),
                ('csv', models.PositiveIntegerField()),
                ('expiration', models.DateField(default='MM/YY')),
                ('card_holder', models.CharField(max_length=250)),
            ],
        ),
    ]
